### DISCUSSION TITLE
Remove default annotations and sort

### DISCUSSION THREAD

**Discussion by dkirrane** [dekorateio/dekorate#1282] [General]
Is there a way to disable the default annotations `app.dekorate.io/vcs-url` and `app.dekorate.io/commit-id`?

Like wise is there a way to have them sorted?

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    foo: bar
    app.dekorate.io/commit-id: abc27d46fa8456bf93edbadb1231bfeb3c837ghh
```
