### ISSUE TITLE
Dekorate does not resolve well the properties that uses expressions in application yaml files

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#1057]
When having the following property:

`application.yaml`:
```
server.port: ${greeting-service.port}
```

The generated resource is always setting the port to 8080:

```yaml
name: spring-boot-istio-distributed-tracing-greeting-service
ports:
  - containerPort: 8080
    name: http
    protocol: TCP
```

However, when having the same properties in a `application.properties` file, everything works fine:

`application.properties`:
```
server.port=${greeting-service.port}
```

Note that we're using the `resources` Maven plugin to filter these resources:

```xml
<build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
</build>
```
