### ISSUE TITLE
The "protocol" property is not being set in the generated Service resources

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#1068]
The generated Services resources are not setting the protocol:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 5c4720d733cd2bd9bea27be621104d38e4609910
  labels:
    app.kubernetes.io/name: name
  name: name
  namespace: namespace
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP            # This is not being set!
  selector:
    app.kubernetes.io/name: name
  type: ClusterIP
```

Moreover, the Protocol is an enum with only two values: TCP, UDP. It needs to incorporate also the new values: SCTP, HTTP and PROXY. 

# Additional links
- Supported protocols: https://kubernetes.io/docs/concepts/services-networking/service/#protocol-support).
- Example of SCTP: https://docs.openshift.com/container-platform/4.9/networking/using-sctp.html
