### ISSUE TITLE
Allow configuring Ingress rules 

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#1083]
At the moment, Dekorate will generate an Ingress resource with only one host and path, similar to:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-14 - 15:06:39 +0000
  labels:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
  name: quarkus-app
  namespace: my-namespace
spec:
  rules:
    - host: myhost.example.com
      http:
        paths:
          - backend:
              service:
                name: quarkus-app
                port:
                  name: http
            path: /newroot
            pathType: Prefix
```

However, we should also support adding more rules using the properties:

```
# This is to customize the generated rule
dekorate.kubernetes.ingress.rules[0].host=myhost.example.com
dekorate.kubernetes.ingress.rules[0].path=/anotherpath
dekorate.kubernetes.ingress.rules[0].pathType=ImplementationSpecific

# Or add a new rule
dekorate.kubernetes.ingress.rules[1].host=myanotherhost.example.com
dekorate.kubernetes.ingress.rules[1].path=/path
# by default, path type is Prefix

# By default, the service, used by the above rules, is the one exposed by the application, but we should also allow users to specify a different one:
dekorate.kubernetes.ingress.rules[1].host=myanotherhost.example.com
dekorate.kubernetes.ingress.rules[1].path=/path
dekorate.kubernetes.ingress.rules[1].service=my-other-service
dekorate.kubernetes.ingress.rules[1].port-name=http
```

This issue is related to this Quarkus issue: https://github.com/quarkusio/quarkus/issues/26747
