### ISSUE TITLE
Knative configurator replaces all the port names to http1

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#1119]
When the container contains more than one port like:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - image: my-image
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9000
              name: custom
              protocol: TCP
```

When applying Dekorate, the ports got modified as:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - image: my-image
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
            - containerPort: 9000
              name: http1
              protocol: TCP
```

The expected output should be that only the HTTP port is renamed to "http1".
