### ISSUE TITLE
Dekorate exposes all the ports in the generated Ingress resource

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#1123]
When having multiple ports in your application, the generated Ingress resource would look:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
spec:
  rules:
    - host: prod.svc.url
      http:
        paths:
          - backend:
              service:
                name: app
                port:
                  name: http
            path: /
            pathType: Prefix
          - backend:
              service:
                name: app
                port:
                  name: https
            path: /
            pathType: Prefix
```

This is incorrect as the same path is used for both ports. Only the HTTP should be used unless the user wants to use the other. (We need a new property for selecting this).
