### ISSUE TITLE
Where does the label Group is coming from ?

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#196]
## Question

How do you generate (= rule coded) the labels within the `Component METADATA yaml/json` using ap4k ?  Where does the label Group is coming from ?

```
  labels:
   app: "fruit-backend-sb"
   version: "0.0.1-SNAPSHOT"
   group: "dabou"
```
