### ISSUE TITLE
Link.spec.componentName is missing

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#225]
### Issue

Since the refactoring of the project and the separation of the component from the link, the following [mandatory field](https://github.com/snowdrop/component-operator/blob/master/pkg/apis/component/v1alpha2/link_types.go#L17
pkg/apis/component/v1alpha2/link_types.go:17) is missing 

Ap4k is generating such info using the component-operator-demo/fruit-client-sb project

```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Link"
  metadata:
    name: "link-to-fruit-backend"
  spec:
    name: "link-to-fruit-backend"
    kind: "Env"
    ref: ""
    envs:
    - name: "OPENSHIFT_ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"
```

which should be

```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Link"
  metadata:
    name: "link-to-fruit-backend"
  spec:
    name: "link-to-fruit-backend"
    kind: "Env"
    componentName: "fruit-client-sb"
    ref: ""
    envs:
    - name: "OPENSHIFT_ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"

```

**Comment by aureamunoz** [comment]
So the `spec.componentName` field of a Link should be filled with the name of the component where the object link is being injected, right?
The field https://github.com/snowdrop/component-operator/blob/master/pkg/apis/component/v1alpha2/link_types.go#L17 is not currently mandatory. Since the link object is now independent of the Component, shouldn't it be mandatory?

**Comment by aureamunoz** [comment]
The `.spec.componentName` is gathered with the value of `targetcomponentname` field from annotation config --> [view the code](https://github.com/aureamunoz/ap4k/commit/8d9f34ba54223bd6c98b94e4dd1787bc0468e8dd#diff-8c0cffd6ad594b6bf4320914a6694c83R57)
For example:
If we have a link annotation like:
```
@Link(
    name = "link-to-database",
    targetcomponentname = "fruit-backend-sb",
    kind = Kind.Secret,
    ref = "postgresql-db")
```
will produce:
```
 apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Link"
  metadata:
    name: "link-to-fruit-backend"
  spec:
    name: "link-to-fruit-backend"
    kind: "Env"
    componentName: "fruit-client-sb"
    ref: ""
    envs:
    - name: "OPENSHIFT_ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"
```
WDYT @cmoulliard ?
