### ISSUE TITLE
Group not being populated by spring boot properties when using application-kubernetes.yml

### ISSUE THREAD

**Issue by spencergibb** [dekorateio/dekorate#250]
I tried
```
dekorate:
  kubernetes:
    serviceType: NodePort
    imagePullPolicy: Always
    group: spencergibb
```
service type and image pull work, but group doesn't work.

I have to do this:
```
@KubernetesApplication( group = "spencergibb" )
```

**Comment by iocanel** [comment]
After further discussion, it seems that this is an issue when configuration is found in `application-kubernetes.yml`.

**Comment by spencergibb** [comment]
Looks like this is working now.

**Comment by Albertoimpl** [comment]
I am having the same issue Spencer had, having to specify the group in the class, with the latest versions:
```
compile 'io.dekorate:kubernetes-spring-starter:0.9.1'
annotationProcessor 'io.dekorate:kubernetes-annotations:0.9.1'
```

**Comment by iocanel** [comment]
@Albertoimpl just curious does it work if you have it inside application.yml?

**Comment by Albertoimpl** [comment]
Thanks for the quick response @iocanel.
If I remove the group from:
```
@KubernetesApplication(group = "albertoimpl")
```
and add it in the `application.yml`:
```
dekorate:
  kubernetes:
    labels:
      - app: myapp
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    serviceType: NodePort
    group: albertoimpl
```

it goes back to: `group: "alberto"`
