### ISSUE TITLE
exposeService = true annotation becomes false within yaml resource

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#254]
## Issue

I discovered a big issue using a fresh build of dekorate. When we seyup this Component annotation where the ​`exposeService = true`
```
@ComponentApplication(
  name = "fruit-backend-sb",
  exposeService = true,
```
​then dekorate generates the following yaml file where exposeService = false
​
```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
 kind: "Component"
 metadata:
  labels:
   app: "fruit-backend-sb"
   version: "0.0.1-SNAPSHOT"
   group: "dabou"
  name: "fruit-backend-sb"
 spec:
  deploymentMode: "dev"
  runtime: "spring-boot"
  version: "2.1.3.RELEASE"
  exposeService: false
```
