### ISSUE TITLE
Invalid value: 600: must be a number between 0 and 0777 (octal)

### ISSUE THREAD

**Issue by longzl2015** [dekorateio/dekorate#264]
I use a `@ConfigMapVolume` in `@KubernetesApplication`. 

```
@KubernetesApplication(
        // ..
        configMapVolumes = @ConfigMapVolume(volumeName = "app", configMapName = "app")
)
``` 

It will generete some code:

```
      spec:
        // ...
        volumes:
        - configMap:
            defaultMode: 600
            name: "app"
            optional: false
          name: "app"
```

and then, I use a commad( kubectl apply -f kubernetes.yml ). 
kubectl will throw a error:

> Invalid value: 600: must be a number between 0 and 0777 (octal).

so, I edit the @ConfigMapVolume. as follows:

```
@KubernetesApplication(
        // ..
        configMapVolumes = @ConfigMapVolume(volumeName = "app", configMapName = "app",,defaultMode = 0600)
)
``` 

but It generate some code:

```
        - configMap:
            defaultMode: 384
            name: "app"
            optional: false
          name: "app"
```

then I exec the command( kubectl apply -f kubernetes.yml )。 
It works well.
