### ISSUE TITLE
buildConfig not generated using annotationless mode

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#270]
## Info

Version of Dekorate: 0.7.2
Gavs:
```
    <dependencies>
        <dependency>
            <groupId>io.dekorate</groupId>
            <artifactId>dekorate-spring-boot</artifactId>
            <version>0.7.2</version>
        </dependency>

        <dependency>
            <groupId>io.dekorate</groupId>
            <artifactId>component-annotations</artifactId>
            <version>0.7.2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
```
## Issue

The buildconfig is not generated using `annotationless` mode

Config = Application.properties 

```
dekorate.component.deploymentMode=build
dekorate.component.exposeService=true
dekorate.component.envs[0].name=ENDPOINT_BACKEND
dekorate.component.envs[0].value=http://fruit-backend-sb:8080/api/fruits
```

Generated
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Component"
  metadata:
    name: "myproject"
  spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    exposeService: true
    envs:
    - name: "ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"

```

**Comment by cmoulliard** [comment]
From Auri

`What should I do if lack of .git? Generate an empty BuildConfig section?`

From Charles
This is a great question @Auri We could generate it and add a WARNING message to mention that no git repo is available locally and should be then created AND we should add a link pointing to the doc to explain how to modify the buildconfig parameters. WDYT @Auri @Chris Laprun @Ioannis Canellos ...

From Ioannis Canellos
Does it make sense to have a build config if we don't have the project on scm?

From Charles

Your point is correct. If no git repo exists, then it don't make sense that we generate it. But, if the developer is not aware about this option (= deploymentMode = build -> buildConfig), then my idea is perhaps the best or a good strategy. WDYT ? @aureamunoz @iocanel @metacosm

**Comment by aureamunoz** [comment]
This issue is caused by the lack of .git.
if deploymentMode = build then buildConfig contains some relevant infos concerning this build:
``` 
buildConfig:
      type: "docker"
      uri: "https://github.com/dekorateio/dekorate.git"
      ref: "issue-270-buildconfig"
      contextPath: "examples/"
      moduleDirName: "component-example-annotationless-properties"
```
 If no git repo exists, then it don't make sense that we generate the whole `buildConfig` element? or we could generate the others fields? WDYT @iocanel @cmoulliard @metacosm
