### ISSUE TITLE
deploymentMode is not overrided by conf

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#272]
The `deploymentMode` element is never override by configuration either in annotation or annotationless mode.
`DeploymentMode` takes a value (`dev`) by default but it should be override by specific configuration if present.
Annotiation mode:
`@ComponentApplication(name = "hello-world", deploymentMode = DeploymentMode.build, exposeService = true, envs = @Env(name = "key1", value = "val1"))
`
should generate:
```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Component"
  metadata:
    name: "component-it-issue-71"
  spec:
    deploymentMode: "build"
    exposeService: true
    envs:
    - name: "key1"
      value: "val1"
```

Annotiationless mode:
application.properties like
```
dekorate.component.name=annotationless component
dekorate.component.envs[0].name=key_from_properties
dekorate.component.envs[0].value=value_from_properties
dekorate.component.buildType=docker
dekorate.component.deploymentMode=build
```
should produce:
```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Component"
  metadata:
    labels:
      app: "component-example-annotationless-properties"
      version: "0.7-SNAPSHOT"
      group: "amunozhe"
    name: "component-example-annotationless-properties"
  spec:
    deploymentMode: "build"
    runtime: "spring-boot"
    version: "2.1.0.RELEASE"
    exposeService: false
```
