### ISSUE TITLE
Provide the component.spec.port

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#275]
## Enhancement request

By default, the operator is adding (= hard coding) a value for the service and/or ingress route to be created - `8080`. This information should be communicated according to the framework of the runtime the port to be used using the field

`component.spec.port`

Don't wrap the port number (which is a go int32) with double quotes but instead

```
spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.3.RELEASE"
    exposeService: true
    port: 8080
```
