### ISSUE TITLE
the version field generated by @KubernetesApplication is annoying. 

### ISSUE THREAD

**Issue by longzl2015** [dekorateio/dekorate#280]
I use the following example in springboot:

```
@KubernetesApplication(
        registry = "harbor.aa",
        group = "sl",
        name = "app",
        imagePullPolicy = ImagePullPolicy.Always
        ....  // 
)
```

The @KubernetesApplication will generate the yaml:

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "app"
      version: "1.1.1.0"
      group: "sl"
    name: "app"
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: "app"
        version: "1.1.1.0"
        group: "sl"
    template:
      metadata:
        labels:
          app: "app"
          version: "1.1.1.0"
          group: "sl"
    // ...
```

`kubectl apply -f` works well.

But, when I update the version in pom.xml :
1.1.1.0   => 1.1.1.1

generate kubernetes.yml again.

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "app"
      version: "1.1.1.1"
      group: "sl"
    name: "app"
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: "app"
        version: "1.1.1.1"
        group: "sl"
    template:
      metadata:
        labels:
          app: "app"
          version: "1.1.1.1"
          group: "sl"
    // ...
```

then  `kubectl apply -f`  again . It will show an error:

```
The Deployment "app" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"app", "group":"sl", "version":"1.1.1.1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Is it possible that: 

when version in @KubernetesApplication is empty, @KubernetesApplication do not generate selector.matchLabels.version
