### ISSUE TITLE
buildConfig should not be generated by default

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#292]
Since we use the `deploymentMode = dev` mode by default we shouldn't generate the build config by default.

that's what it's generated from a scaffolded project for example:
```
buildConfig:
      type: "s2i"
      url: null
      ref: "master"
      contextPath: ""
      moduleDirName: "foo"
```
That doesn't make sense, buildConfig should not be generated.
