### ISSUE TITLE
configMapVolume example

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#306]
There is a configMapVolume annotation under k8s project. The goal of this ticket is to:

- [x]  Create an example about How to use a configMap and mount it as volume to the Deployment, DeploymentConfig - https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files
- [x]  Document how to use ConfigMap
- [ ] Review/Enhance the logic of dekorate to offer the possibility to copy additional yml resources files such as ConfigMap, Secret, ... to the target dekorate folder

**Comment by cmoulliard** [comment]
@brunoNetId

**Comment by geoand** [comment]
I haven't been part of the discussions but I am a little confused by the description of the ticket. Is the goal to create an example in the dekorate codebase (similar to the examples we already have) and add some documentation (like a README) to that example?
Are we assuming that users know very little about Kubernetes (for example they have only heard of a ConfigMap but haven't really used it)? I am asking this because some the steps in the ticket seem to be about pretty basic Kubernetes functionality

**Comment by cmoulliard** [comment]
> but I am a little confused by the description of

Description is clear as we must do 3 tasks: create an example, document and certainly improve current dekorate logic to create a ConfigMap from a developer's file

**Comment by geoand** [comment]
> > but I am a little confused by the description of
> 
> Description is clear as we must do 3 tasks: create an example, document and certainly improve current dekorate logic to create a ConfigMap from a developer's file

Well it's not that clear to me (as a person who has less context) which is why I asked :)

**Comment by geoand** [comment]
> * [ ]  Review/Enhance the logic of dekorate to offer the possibility to copy additional yml resources files such as ConfigMap, Secret, ... to the target dekorate folder

Can you please provide an example of what you have in mind?

**Comment by cmoulliard** [comment]
> an example of what you have in mind?

See k8s doc as mentioned within this ticket description -> https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files

**Comment by aureamunoz** [comment]
Hi @cmoulliard,
I think [this link](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files) doesn't correspond to the description _"Create an example about How to use a configMap and mount it as volume to the Deployment, DeploymentConfig"_ and the example should show rather [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume).

Un first extract of example could be:
```
@KubernetesApplication(configMapVolumes = @ConfigMapVolume(volumeName = "config-volume", configMapName = "special-config"))
@SpringBootApplication
public class Main {

  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }
}
```
Would generate a Deployment as bellow:
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "kubernetes-example"
      version: "0.8-SNAPSHOT"
      group: "amunozhe"
    name: "kubernetes-example"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "kubernetes-example"
        version: "0.8-SNAPSHOT"
        group: "amunozhe"
    template:
      metadata:
        labels:
          app: "kubernetes-example"
          version: "0.8-SNAPSHOT"
          group: "amunozhe"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "amunozhe/kubernetes-example:0.8-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "kubernetes-example"
        volumes:
        - configMap:
            defaultMode: 384
            name: "special-config"
            optional: false
          name: "config-volume"
```
WDYT @cmoulliard?
