### ISSUE TITLE
port is not generated and exposeService becomes = false

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#313]
## Issue

port is not generated and exposeService becomes = false even if we define within the java class this annotation

```
import io.dekorate.halkyon.annotation.HalkyonComponent;
import io.dekorate.halkyon.annotation.HalkyonLink;
import io.dekorate.halkyon.model.Kind;
import io.dekorate.kubernetes.annotation.Env;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point to the application.
 */
@SpringBootApplication
@HalkyonComponent(
    name = "fruit-client-sb",
    exposeService = true
)
@HalkyonLink(
    name = "link-to-fruit-backend",
    componentName = "fruit-client-sb",
    kind = Kind.Env,
    envs = @Env(
        name = "ENDPOINT_BACKEND",
        value = "http://fruit-backend-sb:8080/api/fruits"
    )
)
```

and server port under the application.yml file
```
server:
  port: 8080

# Endpoint property to access the backend microservice
endpoint:
  fruit: ${ENDPOINT_BACKEND}

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    deploymentMode: build
```

Generated
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "fruit-client-sb"
    name: "fruit-client-sb"
  spec:
    deploymentMode: "build"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    exposeService: false
    buildConfig:
      type: "s2i"
      url: "git+ssh://git@github.com/halkyonio/operator"
      ref: "master"
      contextPath: "demo/"
      moduleDirName: "fruit-client-sb"
- apiVersion: "halkyon.io/v1beta1"
  kind: "Link"
  metadata:
    name: "link-to-fruit-backend"
  spec:
    componentName: "fruit-client-sb"
    kind: "Env"
    ref: ""
    envs:
    - name: "ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"
```

See project: https://github.com/halkyonio/operator/blob/master/demo/fruit-client-sb/src/main/resources/application.yml#L2

**Comment by cmoulliard** [comment]
The problem can be resolved if we add `    exposeService: true` to the application.yml file

**Comment by geoand** [comment]
I haven't followed the latest discussions on the design of annotation-less mode, so I am not sure if this behavior is expected or not.

What I am observing, is that when one mixes Dekorate properties and annotations, all the "configuration" from annotations is lost.

In this super simple example:

```
@HalkyonComponent(exposeService = true, name = "my-example")
@SpringBootApplication
public class Main {

  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }

}
```

when `application.yaml` contains only:

```
server:
    port: 9090
```

then the result is:

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "my-example"
    name: "my-example"
  spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.0.RELEASE"
    exposeService: true
    port: 9090
```

In this example all the dekorate "configuration" is taken from the annotation.

However if I change `application.yaml` to:

```
server:
    port: 9090

dekorate:
    component:
        deploymentMode: build
```

then the result is:

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "halkyon-example"
    name: "halkyon-example"
  spec:
    deploymentMode: "build"
    runtime: "spring-boot"
    version: "2.1.0.RELEASE"
    exposeService: false
    buildConfig:
      type: "s2i"
      url: "https://github.com/dekorateio/dekorate.git"
      ref: "master"
      contextPath: "examples/"
      moduleDirName: "halkyon-example"
```

which to me suggest that annotations are not considered at all because we supplied some dekorate "configuration" via `application.properties`.
Like I said, I am not sure if this is by design or not. @aureamunoz @metacosm WDYT?

Note: I tested all the above from `master`
