### ISSUE TITLE
Generate halkyon.yml file for maven project containing src/main/resources

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#316]
## Question

Could dekorate generate a halkyon.yml file for a maven project containing only `src/main/resources` folder with an `application.yml` file like this ?

```
dekorate:
  capability:
    category: "database"
    kind: "postgres"
    version: "10"
    parameters:
      - name: "DB_USER"
        value: "admin"
      - name: "DB_PASSWORD"
        value: "admin"
      - name: "DB_NAME"
        value: "sample-db"
```
