### ISSUE TITLE
Content generated for halkyon : annotationless vs annotations is different

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#327]
## Issues

- Version used: 0.8.1 using halkyon starter
- Content generated for halkyon : annotationless vs annotations is different

### Java Annotations

```
@HalkyonComponent(
    name = "fruit-backend-sb"
)
@HalkyonLink(
    name = "link-to-database",
    componentName = "fruit-backend-sb",
    type = Type.Secret,
    ref = "postgres-db-config")
@HalkyonCapability(
    name = "postgres-db",
    category = "database",
    type = "postgres",
    version = "10",
    parameters = {
       @Parameter(name = "DB_USER", value = "admin"),
       @Parameter(name = "DB_PASSWORD", value = "admin"),
       @Parameter(name = "DB_NAME", value = "sample-db"),
    }
)
```

Generated

```
---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Capability"
    metadata:
      name: "postgres-db"
    spec:
      category: "database"
      kind: "postgres"
      version: "10"
      parameters:
        - name: "DB_USER"
          value: "admin"
        - name: "DB_PASSWORD"
          value: "admin"
        - name: "DB_NAME"
          value: "sample-db"
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Component"
    metadata:
      labels:
        app: "fruit-backend-sb"
      name: "fruit-backend-sb"
    spec:
      deploymentMode: "build"
      runtime: "spring-boot"
      version: "2.1.6.RELEASE"
      exposeService: true
      buildConfig:
        type: "s2i"
        url: "git+ssh://git@github.com/halkyonio/operator"
        ref: "master"
        contextPath: "demo/"
        moduleDirName: "fruit-backend-sb"
      port: 8080
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Link"
    metadata:
      name: "link-to-database"
    spec:
      componentName: "fruit-backend-sb"
      kind: "Secret"
      ref: "postgres-db-config"
```

### Annotationless

```
server:
  port: 8080

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    name: fruit-backend-sb
    deploymentMode: dev
    exposeService: true
  link:
    name: link-to-database
    componentName: fruit-backend-sb
    type: Secret
    ref: postgres-db-config
  capability:
    name: postgres-db
    category: database
    type: postgres
    version: "10"
    parameters:
    - name: DB_USER
      value: admin
    - name: DB_PASSWORD
      value: admin
    - name: DB_NAME
      value: sample-db

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
```

Generated

```
---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Capability"
    metadata:
      name: "postgres-db"
    spec:
      category: "database"
      type: "postgres"
      version: "10"
      parameters:
        - name: "DB_USER"
          value: "admin"
        - name: "DB_PASSWORD"
          value: "admin"
        - name: "DB_NAME"
          value: "sample-db"
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Component"
    metadata:
      labels:
        app: "fruit-backend-sb"
      name: "fruit-backend-sb"
    spec:
      deploymentMode: "dev"
      runtime: "spring-boot"
      version: "2.1.6.RELEASE"
      exposeService: true
      buildConfig:
        type: "s2i"
        url: "https://github.com/halkyonio/operator.git"
        ref: "master"
        contextPath: "demo/"
        moduleDirName: "fruit-backend-sb"
      port: 8080
  - apiVersion: "halkyon.io/v1beta1"
    kind: "Link"
    metadata:
      name: "link-to-database"
    spec:
      componentName: "fruit-backend-sb"
      type: "Secret"
      ref: "postgres-db-config"
```

![Screenshot 2019-08-27 11 59 03](https://user-images.githubusercontent.com/463790/63762139-99241480-c8c2-11e9-8cbe-7820887d7d20.png)
