### ISSUE TITLE
Speciffy Halkyon runtime and version

### ISSUE THREAD

**Issue by jponge** [dekorateio/dekorate#389]
I have been able to deploy a Vert.x component with the following hand-crafted resource:

```yaml
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: dekorate-and-vertx
spec:
  runtime: vert.x
  version: 3.8.3
  deploymentMode: dev
  port: 8080
  exposeService: true
```

Now I would like to have fun with `hal` and _Dekorate_, so I have this (annotation-less) file:

```yaml
dekorate:

  kubernetes:
    serviceType: "LoadBalancer"
    ports:
      - name: "http"
        containerPort: 8080

  component:
    name: "dekorate-and-vertx"
    exposeService: true
```

which generates the following `target/classes/META-INF/dekorate/halkyon.yml`:

```yaml
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "dekorate-and-vertx"
      version: "0.0.0-SNAPSHOT"
      group: "jponge"
    name: "dekorate-and-vertx"
  spec:
    deploymentMode: "dev"
    version: "0.0.0-SNAPSHOT"
    exposeService: true
    port: 8080
```

It is missing runtime info, causing Halkyon to fail, and I cannot specify this with _Dekorate_.
