### ISSUE TITLE
Specify external registry

### ISSUE THREAD

**Issue by jponge** [dekorateio/dekorate#420]
It would be useful to have the option to specify a registry.

I am trying to reproduce this with Dekorate, but this is not possible:

```yaml
spec:
  containers:
    - image: localhost:32000/rain-service
```

**Comment by iocanel** [comment]
You should be able to specify a registry with something like:

    dekorate:
      docker:
        registry: localhost:32000

**Comment by jponge** [comment]
Given `application.yml`:

```yaml
dekorate:
  kubernetes:
    serviceType: LoadBalancer
    ports:
      - name: HTTP
        containerPort: 8080
    liveness-probe:
      http-action-path: /health
      initial-delay-seconds: 3
      period-seconds: 5
  docker:
    registry: localhost:32000

```

I do not get any mention of the registry:

```yaml
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "rain-service"
    version: "0-SNAPSHOT"
    group: "jponge"
  name: "rain-service"
spec:
  ports:
  - name: "HTTP"
    port: 8080
    targetPort: 8080
  selector:
    app: "rain-service"
    version: "0-SNAPSHOT"
    group: "jponge"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "rain-service"
    version: "0-SNAPSHOT"
    group: "jponge"
  name: "rain-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rain-service"
      version: "0-SNAPSHOT"
      group: "jponge"
  template:
    metadata:
      labels:
        app: "rain-service"
        version: "0-SNAPSHOT"
        group: "jponge"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "jponge/rain-service:0-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        name: "rain-service"
        ports:
        - containerPort: 8080
          name: "HTTP"
          protocol: "TCP"
```
