### ISSUE TITLE
container-port vs containerPort

### ISSUE THREAD

**Issue by jponge** [dekorateio/dekorate#421]
The documentation at https://github.com/dekorateio/dekorate/blob/master/assets/config.md for `Port` types mentions `container-port`.

However when you use it for a Kubernetes port declaration as in:

```yaml
dekorate:
  kubernetes:
    serviceType: LoadBalancer
    ports:
      - name: HTTP
        container-port: 8080
```

it does not work, you need to use `containerPort`.
