### ISSUE TITLE
Manage Compute Resources for Containers

### ISSUE THREAD

**Issue by ferasodh** [dekorateio/dekorate#429]
Hi,
Is it possible to specify container compute resources via configuration. I can't find any configs related to resources. I want to generate the following yml:
```
resources:
                  requests:
                      memory: "300Mi"
                      cpu: "100m"
                  limits:
                      memory: "512Mi"
                      cpu: "1"
```

Thanks for help
