### ISSUE TITLE
[Feature] Able to generate a resource item instead of a list

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#45]
### Feature's request

As a user, I would like to have the possibility to get a generated resource created as an item and not as as a list

What is currently populated 
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: ""
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    image: []
    env:
    - name: "key1"
      value: "val1"
    - name: "key1"
      value: "val1"
    feature: []
    link: []
    service: []
```

What I want 
```
apiVersion: component.k8s.io/v1alpha1
kind: "Component"
metadata:
  annotations: {}
  labels: {}
  name: ""
spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    image: []
    env:
    - name: "key1"
      value: "val1"
    feature: []
    link: []
    service: []
```
