### ISSUE TITLE
Support Configuring Deployment Strategy for Deployments such as Rolling Updates / Recreate

### ISSUE THREAD

**Issue by dmakeroam** [dekorateio/dekorate#590]
Hi @iocanel,

Is it possible to specify deployment strategy via configuration? I can't find any configs related to the deployment strategy. I want to generate the following yml:

```
dekorate:
    kubernetes:
          deployment-strategy: 
                 type: RollingUpdate / Recreate
                 maxSurge: 2
                 maxUnavailable: 0
```

Thanks for help
