### ISSUE TITLE
Allow generating helm charts

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#673]

**Comment by Sgitario** [comment]
@iocanel , Charles asked me to do this, is it fine for you to assign this issue to me?

**Comment by Sgitario** [comment]
@iocanel @aureamunoz I would like to clarify how the generated charts elements will be used in Dekorate. To be precise, the `values.yaml` file.

To give some context, Helm works using basically three elements:
- `Chart.yaml` - the chart metadata like name, version, dependencies, etc. Example:

```yaml
---
apiVersion: v1
name: myChart
version: 2.7-SNAPSHOT

```

- `values.yaml` to parametrize the template values of the Chart. Example:

```yaml
replicas: 1
expose: false
limitResources:
  memory: ""
  cpu: ""
requestResources:
  memory: ""
  cpu: 1m
name: helm-example
```

- `templates/*.yaml` the resources to load. One resource can use the values as for example:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: 2.7-SNAPSHOT
    app.openshift.io/runtime: spring-boot
  name: {{ .Values.name }}
// ...
```

Ok, so the question is ... how can we interpolate the attributes from `values.yaml` to the yaml files? By means, how do we know that the `service.metadata.labels."app.kubernetes.io/name" is taken from `{{ .Values.name }}`.

I don't think we can do any magic to automatically map the Dekorate values (from annotations and properties) to the `{{ .Values.xxx}}` Helm translation.

I see a few approaches here:

## Do the same as in Jkube

Jkube fully delegates the parameters to replace to users. For doing this, the user needs to provide a `values template.yaml` file with the values to use, for example:

```yaml
kind: Template
parameters:
  - name: limits_memory
    value: 512Mi
```

And then, the user is responsible to use the value `${limits_memory}` in the final resources, which in Dekorate would mean to use something like:

```
dekorate.kubernetes.limit-resources.memory=${limits_memory}
```

And then, the framework is replacing `${limits_memory}` to `{{ .Values.limits_memory }}`.

## Support a set of values only

Another option could be to support only a few values options like the `name` or `builderImage` (for s2i). 
Therefore, if the user have configured the s2i value `builderImage` using a Dekorate annotation or property, we can detect it and have a rule that knows where this property needs to be interpolated to (in BuildConfig).

However, this solution brings a huge maintenance cost.

## A mix of the above two solutions

Support a set known values like name (for metadata names) or builderImage (for s2i), but allow users to fully customize more as done in Jkube.

# Conclusions

What do you think it's the best solution for this problem?

Thanks both!
