### ISSUE TITLE
Static field added to a generated CRD

### ISSUE THREAD

**Issue by ppatierno** [dekorateio/dekorate#713]
When generating a CRD starting from a POJO, I see the following static fields showing up that should not be there because internals and not part of the POJO declaration.

```yaml
LOG:
          properties:
            ROOT_LOGGER_NAME:
              type: string
          type: object
        NAMESPACE_SCOPE:
          type: string
        CLUSTER_SCOPE:
          type: string
        singular:
          type: string
        crdName:
          type: string
        scope:
          type: string
        plural:
          type: string
```

**Comment by ppatierno** [comment]
@iocanel latest 2.0.0.beta2 fixes the public static fields like `NAMESPACE_SCOPE` but it still leave the rest in the generated YAML. I still see this:

```yaml
singular:
          type: string
        crdName:
          type: string
        scope:
          type: string
        plural:
          type: string
```
