### ISSUE TITLE
Invalid generated version when version is defined using double quotes

### ISSUE THREAD

**Issue by pgressa** [dekorateio/dekorate#742]
When gradle is used and the version is defined using double quotes
```
....
version = "0.1"
...

```

then generated resources contains invalid values like in labels and most importantly in image:
```
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
      labels:
        app.kubernetes.io/name: producer-service
        app.kubernetes.io/version: '"0.1"'
        app: producer-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: pgressa/producer-service:"0.1"
        imagePullPolicy: Always
```

The issue is here:
https://github.com/dekorateio/dekorate/blob/master/core/src/main/java/io/dekorate/project/GradleInfoReader.java#L182-L217

There should also be a replacement for double quotes, not just simple quotes.
