### ISSUE TITLE
Deploy hook doesn't apply the replicas

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#766]
The replicas are not taken into account, when deploying with the hook, I have also a pod thought in the manifests replicas: 4.

Command launched on the root folder of a project that I would like to deploy: 

`mvn clean package -Ddekorate.build=true -Ddekorate.push=true -Ddekorate.deploy=true`

The k8s manifest generated:
```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 07d8224b727a8e2954ded381d78e3acc3b77bfb7
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 07d8224b727a8e2954ded381d78e3acc3b77bfb7
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/name: demo
  name: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
      app.kubernetes.io/name: demo
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 07d8224b727a8e2954ded381d78e3acc3b77bfb7
      labels:
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        app.kubernetes.io/name: demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/amunozhe/demo:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 07d8224b727a8e2954ded381d78e3acc3b77bfb7
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: demo
spec:
  rules:
    - host: sb-demo.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: demo
                port:
                  name: http
            path: /
            pathType: Prefix
```

When we get the pods, we have only one: 
```
kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
demo-764fd57c66-bprhl   1/1     Running   0          21s
```
