### ISSUE TITLE
The kubernetes service manifest generated contains duplicate values for port HTTP and HTTPS

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#775]
## Issue

The kubernetes service manifest generated contains duplicate values for port HTTP and HTTPS using either dekorate 2.3.2 or 2.3.3 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: springboot-dekorate-annotation
    runtimedb: mysql
    app.kubernetes.io/version: 2.0.0-SNAPSHOT
    app.openshift.io/runtime: spring-boot
  name: springboot-dekorate-annotation
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 80
    targetPort: 8443
```

The following error is reported during the S2I deployment

```
The Service "springboot-dekorate-annotation" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", Port:80, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```

when the class is annotated as such

```
import io.dekorate.openshift.annotation.OpenshiftApplication;
import io.dekorate.s2i.annotation.S2iBuild;
import io.dekorate.kubernetes.annotation.Probe;
import io.dekorate.kubernetes.annotation.Label;
import io.dekorate.kubernetes.annotation.Port;
import io.dekorate.kubernetes.annotation.Env;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@OpenshiftApplication(name="springboot-dekorate-annotation",
                      expose=true,
                      replicas=2,
                      livenessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=60,periodSeconds=3,timeoutSeconds=1),
                      readinessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=10,periodSeconds=10,timeoutSeconds=1),
                      labels={@Label(key="runtimedb",value="mysql")},
                      ports={@Port(name="http",containerPort=8080),
                             @Port(name="https",containerPort=8443),
                             @Port(name="jolokia",containerPort=8778)
                            },
                     envVars={@Env(name="ENV_VAR",value="X_Y_Z")}
                    )
@S2iBuild(builderImage="registry.access.redhat.com/openjdk/openjdk-11-rhel7:latest",
          buildEnvVars={@Env(name="BUILD_EN_VAR",value="A_B_C")}
         )
@SpringBootApplication
public class RestApplication {

	public static void main(String[] args) {
		SpringApplication.run(RestApplication.class, args);
	}
}
```

**Comment by cmoulliard** [comment]
A temporary workaround is to define the `hostPort` of the HTTPS service as such:

```
@OpenshiftApplication(name="springboot-dekorate-annotation",
                      expose=true,
                      replicas=2,
                      livenessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=60,periodSeconds=3,timeoutSeconds=1),
                      readinessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=10,periodSeconds=10,timeoutSeconds=1),
                      labels={@Label(key="runtimedb",value="mysql")},
                      ports={@Port(name="http",containerPort=8080),
                             @Port(name="https",containerPort=8443,hostPort=8443),
                             @Port(name="jolokia",containerPort=8778)
                            },
```

**Comment by cmoulliard** [comment]
Logic changed between [Dekorate 1.x](https://github.com/dekorateio/dekorate/blob/1.0.3/core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java)
```
private ServicePort toServicePort(Port port) {
    return new ServicePortBuilder()
      .withName(port.getName())
      .withPort(port.getContainerPort())
      .withTargetPort(new IntOrString(port.getHostPort() > 0 ? port.getHostPort() : port.getContainerPort()))
      .build();
  }
```
and [Dekorate 2.x](https://github.com/dekorateio/dekorate/blob/2.3.2/core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java#L68-L75)
```
  private ServicePort toServicePort(Port port) {
    return new ServicePortBuilder()
        .withName(port.getName())
        .withNewTargetPort(port.getContainerPort())
        .withPort(port.getHostPort() != null && port.getHostPort() > 0 ? port.getHostPort()
            : (Ports.isWebPort(port) ? 80 : port.getContainerPort()))
        .build();
  }
```
**Problem**: The new logic here is not correct apparently `(Ports.isWebPort(port) ? 80 : port.getContainerPort()))`

**Comment by cmoulliard** [comment]
So, the new condition added to `withPort`
```
  public static boolean isWebPort(Port port) {
    if (webPortNames().contains(port.getName())) {
      return true;
    }
    if (webPortNumbers().contains(port.getContainerPort())) {
      return true;
    }
    return false;
  }
```
will return `true` for both port name `http` and `https` and by consequence, the port of the service definition will include twice `80` as port value.

The result is even worst if you change the port name from `http` to `web` as now we got 3 times the `port: 80` 

```
ports={@Port(name="web",containerPort=8080),
                             @Port(name="https",containerPort=8443),
```
-->
```
kind: service
...
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: web
    port: 80
    targetPort: 8080
  - name: https
    port: 80
    targetPort: 8443
```
