### ISSUE TITLE
ImageStream not generated with JIB default configuration and `openshift-spring-starter`

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#791]
This causes the applicaciont is not deployed correctly on OpenShift.
Given a Spring Boot application with Dekorate `openshift-spring-starter` and `jib-annotations` dependencies and the following configuration in the `application.properties` file:
```
dekorate.s2i.enabled=false
```
When OpenShift descriptor is generated, it doesn't contain the `ImageStream`:
```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/commit-id: 6c47dbc983f1993699c5da471ea72f06c1cfed44
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: spring-boot-on-openshift-with-jib-example
    app.kubernetes.io/version: 2.4-SNAPSHOT
    app.openshift.io/runtime: spring-boot
  name: spring-boot-on-openshift-with-jib-example
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-boot-on-openshift-with-jib-example
    app.kubernetes.io/version: 2.4-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.dekorate.io/commit-id: 6c47dbc983f1993699c5da471ea72f06c1cfed44
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: spring-boot-on-openshift-with-jib-example
    app.kubernetes.io/version: 2.4-SNAPSHOT
    app.openshift.io/runtime: spring-boot
  name: spring-boot-on-openshift-with-jib-example
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: spring-boot-on-openshift-with-jib-example
    app.kubernetes.io/version: 2.4-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/commit-id: 6c47dbc983f1993699c5da471ea72f06c1cfed44
        app.openshift.io/vcs-url: <<unknown>>
      labels:
        app.kubernetes.io/name: spring-boot-on-openshift-with-jib-example
        app.kubernetes.io/version: 2.4-SNAPSHOT
        app.openshift.io/runtime: spring-boot
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/amunozhe/spring-boot-on-openshift-with-jib-example:2.4-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
              scheme: HTTP
            successThreshold: 1
          name: spring-boot-on-openshift-with-jib-example
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - spring-boot-on-openshift-with-jib-example
        from:
          kind: ImageStreamTag
          name: spring-boot-on-openshift-with-jib-example:2.4-SNAPSHOT
      type: ImageChange
```

The `ImageStream` object is needed for updating the deployment that is using such an image. As result OpenShift is not able to scale the pod up and the app is not deployed.
