### ISSUE TITLE
Override default K8s annotations at Quarkus

### ISSUE THREAD

**Issue by fotisolgr** [dekorateio/dekorate#823]
Hello all,

I am trying to override the default K8s annotations, created by Dekorate, through the `application.yml` file like this with no luck: 

```
 kubernetes:
    annotations:
      app.quarkus.io/commit-id: commit-1
      app.quarkus.io/build-timestamp: today
```

And also by creating a `kubernetes.yml` file inside `src/main/kubernetes/` directory like this with no luck as well: 

```
metadata:
  annotations:
    app.quarkus.io/commit-id: commit-1
    app.quarkus.io/build-timestamp: today
```

Is there a way to override the default K8s annotations or even better to disable them?

Thanks in advance.

**Comment by aureamunoz** [comment]
Hi @fotisolgr

Yes, you can override all the defaults. You can do it either [using annotations](https://github.com/dekorateio/dekorate#kubernetes) or [properties file](https://github.com/dekorateio/dekorate#annotation-less-configuration).

For example, something like adding the `@KubernetesApplication(annotations = @Annotation(key = "foo", value="bar"))` would generate the following descriptor: 
```
...
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      foo: bar
      app.dekorate.io/vcs-url: <<unknown>>
      app.dekorate.io/commit-id: commit-n
    labels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: hello-world
    name: hello-world
...
```
And if you prefer to use properties file the configuration could be: 
```
dekorate.kubernetes.annotations[0].key=foo
dekorate.kubernetes.annotations[0].value=bar
```
With the same result. Note that if you use both, the properties file will override the annotation configured values.
I let you [here](https://github.com/dekorateio/dekorate/blob/main/assets/config.md) the link to all properties that you can configure using dekorate.

Let us know if you need something else.
