### ISSUE TITLE
Support Kubernetes CronJob for Openshift and Kubernetes

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#855]
# Description

One [Cron](https://en.wikipedia.org/wiki/Cron)Job object is like one line of a crontab (cron table) file. It runs a job periodically on a given schedule, written in Cron format.

More context in [kubernetes.io/cron-jobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

# User story

- If user does not set cronjob configuration, then CronJob resource is NOT generated
- If user sets cronjob configuration via properties or annotation, then CronJob resource is generated. 

## Properties

The CronJob spec is defined in [cron-job-v1/#CronJobSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec).

|| Property || Description || Mandatory ||
| name | name of the cronjob | YES |
| schedule | cron expression | YES |
| concurrencyPolicy | cronjob concurrent policy | NO. Default: ALLOW |
| startingDeadlineSeconds | Optional deadline in seconds for starting the job if it misses scheduled time for any reason | NO |
| suspend | This flag tells the controller to suspend subsequent executions, it does not apply to already started executions. | NO. Default: false |
| successfulJobsHistoryLimit | The number of successful finished jobs to retain. | NO. Default: 3 |
| failedJobsHistoryLimit | The number of failed finished jobs to retain. | NO. Default: 1 |
| containers[N].name | name of the container at position `N`  | NO: If not set, Dekorate could add the same one as in the Pod template? |
| containers[N].image | image of the container at position `N`  | NO: If not set, Dekorate could add the same one as in the Pod template? |
| containers[N].command | image of the container at position `N`  | NO: If not set, Dekorate could add the same one as in the Pod template? |
| containers[N].args | image of the container at position `N`  | NO: If not set, Dekorate could add the same one as in the Pod template? |

## How do users configure the cronjob configuration?

Let's see how would look like the cronjob configuration for the mandatory fields only:

- Via properties
```
dekorate.kubernetes.cronjobs[0].name=trigger-batch-process
dekorate.kubernetes.cronjobs[0].schedule=*/1 * * * *
```

- Via annotation
```java
@KubernetesApplication(cronJobs = {@CronJob(name = "trigger-batch-process", schedule = "*/1 * * * *")})
```

In this scenario, Dekorate would generate the following resource:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-batch-process
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          # Same as in the Pod template spec because nothing has been set by the user
          - name: ...
```

If the user only provides the `args` field:

```
dekorate.kubernetes.cronjobs[0].name=trigger-batch-process
dekorate.kubernetes.cronjobs[0].schedule=*/1 * * * *
dekorate.kubernetes.cronjobs[0].containers[0].args=arg from cron job!
```

Then, Dekorate should still use the pod template image configuration, but using the args from above:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-batch-process
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          # Same as in the Pod template spec because nothing has been set by the user
          - name: ...
            args: arg from cron job!
```

Finally, if the user provides all the image configuration as:

```
dekorate.kubernetes.cronjobs[0].name=trigger-batch-process
dekorate.kubernetes.cronjobs[0].schedule=*/1 * * * *
dekorate.kubernetes.cronjobs[0].containers[0].image=xxx
```

Then, Dekorate will NOT use the pod template image configuration, but the user provided:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-batch-process
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger-batch-process-1
            image: xxx
```

# Acceptance criteria
- Add integration tests for Kubernetes and Openshift
- Update documentation with new configuration and section
